services:
  postgres:
    image: postgres:18
    container_name: envcrypt-db
    environment:
      POSTGRES_USER: vijay
      POSTGRES_PASSWORD: vijay
      POSTGRES_DB: envcrypt
    volumes:
      - pgdata:/var/lib/postgresql   # Correct for Postgres 18+
    ports:
      - "5432:5432"

volumes:
  pgdata:
