services:
  api:
    build: .
    environment:
      GOOSE_DRIVER: ${GOOSE_DRIVER}
      GOOSE_DBSTRING: ${DATABASE_URL}
      GOOSE_MIGRATION_DIR: ./internal/db/migrations
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    networks:
      - envcrypt-backend

  postgres:
    image: postgres:18
    container_name: envcrypt-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: envcrypt
    volumes:
      - pgdata:/var/lib/postgresql   # Correct for Postgres 18+
    networks:
        - envcrypt-backend

volumes:
  pgdata:


networks:
  envcrypt-backend:
    driver: bridge